### ISSUE TITLE
line 206:fitEllipse(max_contour1) | max_contour1 not defined

### ISSUE THREAD

**Issue by Chandak01** [RedHenLab/Gesture#1]
python main.py
init done
opengl support available
Traceback (most recent call last):
  File "main.py", line 277, in <module>
`(cx1,cy1,area1,ellipse1,flag1) = getHand(thresh1)
`  File "main.py", line 206, in getHand
`ellipse1 = cv2.fitEllipse(max_contour1)
`NameError: global name 'max_contour1' is not defined

**Comment by Abhinav275** [comment]
Thank you for finding the bug. I have corrected it, let me know if you face any other problem.

**Comment by Chandak01** [comment]
Sure!!
